# Application Name
spring.application.name=hospitalapi
# Server Configuration
server.port=8080
# H2 Database Configuration
# === PostgreSQL Configuration ===

# The database URL, pointing to the 'hospitaldb' you just created
spring.datasource.url=jdbc:postgresql://localhost:5432/hospitaldb

# Your database username (default is postgres)
spring.datasource.username=postgres

# The password you set during PostgreSQL installation
spring.datasource.password=123

# This tells Hibernate to automatically create/update tables
spring.jpa.hibernate.ddl-auto=update

# Specifies the correct SQL dialect for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
